version: '3.2'
services:
  live:
    image: alaien/live-server-nginx-edge:http-flv
    ports:
      - 8880:80
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==worker
      restart_policy:
        condition: on-failure
    environment:
      - PULL_URL=155.94.71.151

  client:
    image: alaien/live-client-springboot:http-flv 
    ports:
      - 80:8000
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==worker
      restart_policy:
        condition: on-failure
    environment:
      - CONFIG_SERVER_URL=http://live-config.herokuapp.com/
