version: '3.2'
services:
  live:
    image: alaien/live-server-nginx-edge:http-flv
    ports:
      - 1935:1935
      - 8099:80
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==worker
      restart_policy:
        condition: on-failure
    environment:
      - PULL_URL=155.94.71.151
